### PR TITLE
Create hi

### PR DESCRIPTION
**Pull request by Meganevra**

### CODE REVIEW

**Comment by Meganevra** [comment]
@Artyko we need to commit our new branch to master branch

**Comment by Meganevra** [comment]
@Artyko Yeah! We did it.
What's happened?
we had the main branch master and 0.1 test branch where we make some changes? then we merge two branches and the changes from 0.1 test branche became to master branch

**Comment by Meganevra** [comment]
default

**Comment by Artyko** [comment]
Greate! Now I propose to make two branches, namely the master (default production-ready) and develop

**Comment by Artyko** [comment]
like this 
00eb029a

**Comment by Artyko** [comment]
More complex model for future work
782a1be3

**Pull request merged**
